server:
  port: 1010
  error:
    include-stacktrace: on_param
    include-message: on_param
spring:
  application:
    name: chatroom
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:chatroom}?${DB_PARAMS}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  h2:
    console.enabled: true

  liquibase:
    enabled: true
#    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    jakarta: debug

    org:
      springframework: debug
      hibernate:
        SQL: debug
        orm.jdbc.bind: trace
    com:
      ensaf:
        chatroom: DEBUG
      zaxxer: WARN