spring:
  application:
    name: chatroom
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://${DB_HOST:localhost}/${DB_NAME:chatroom}?${DB_PARAMS}
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
